#introduction to math lib 
import math
print(math.sqrt(16))
print(math.pow(2,3))
print(math.pi)
print(math.e)
print(math.factorial(5))
print(math.log(10))
print(math.log(10,2))
print(math.log10(10))
print(math.sin(90))
print(math.cos(90))
print(math.tan(45))
print(math.degrees(1.57))
print(math.radians(90))
print(math.ceil(2.3))
print(math.floor(2.3))
print(math.trunc(2.3))
print(math.fabs(-2.3))
print(math.fmod(10,3))
print(math.gcd(10,5))
print(math.isfinite(10))
print(math.isinf(10))
print(math.isnan(10))
print(math.modf(10))
print(math.copysign(10,-1))
print(math.frexp(10))
